### ISSUE TITLE
Current Sensing

### ISSUE THREAD

**Issue by egeKeyvan** [VIPQualityPost/lemon-pepper-stepper#11]
Hello, thanks for the great design. I was trying to order this board from JLCPCB and unfortunately the MAX49925 current sense module seems to be out of stock. 

Do you have any suggestions ? 

Is it possible to change the current sensors with a more widely available part ?

**Comment by VIPQualityPost** [comment]
Yes, they don't have stock, I requested them to add some to inventory but I don't know when they will come. 
If you require it to be assembled, you can arrange with them via Global Sourcing to put the part in your personal inventory (I did this for my boards in the meantime). But actually, if you don't need current sensing, you can leave this part off or place later by hand (it's not too hard if you have a hot air station). The current sensing code is also still in the works.

**Comment by VIPQualityPost** [comment]
And to answer the last part: no, there are no other current sensors which fit on this board. Due to the space constraints, it's really impossible to find any other current sensor which supports common mode voltage +48V and fits within the small space. I was previously using hall-effect based current sensors, but the encoder magnet caused interference, so I can't use any of that type.
